// Sprint #374 BOSS.VIEW.COMMENTARY —
// Manages the editable "Why it worked" / "Action taken" commentary block
// attached to the user's cached boss-view payload.
//
// GET   /api/reports/friday-kpi/boss-view/commentary
//       Returns the saved commentary (or { commentary: null } if unset).
//
// POST  /api/reports/friday-kpi/boss-view/commentary
//       Body: { } — generates fresh commentary via Anthropic Haiku from the
//       caller's current cached boss-view payload + persists. Always
//       overrides any existing commentary (treats as "regenerate").
//
// PATCH /api/reports/friday-kpi/boss-view/commentary
//       Body: { whyWorked?: string, actionTaken?: string }
//       Saves user edits. Marks autoGenerated = false. Does NOT call AI.
//
// All routes are auth-gated. The published-snapshot endpoint reads
// commentary from the cache row at publish time, so this is the single
// source of truth.

import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'
import { getEffectiveOwnerId } from '@/lib/workspace'
import type { BossViewPayload } from '@/lib/reports/boss-view'
import Anthropic from '@anthropic-ai/sdk'

export const runtime     = 'nodejs'
export const maxDuration = 30
export const dynamic     = 'force-dynamic'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const MODEL     = 'claude-haiku-4-5-20251001'

export interface BossViewCommentary {
  whyWorked:     string
  actionTaken:   string
  autoGenerated: boolean
  generatedAt:   string
  model?:        string
}

const TABLE = 'friday_kpi_boss_view_cache'

// ─── GET ────────────────────────────────────────────────────────────────────
export async function GET() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const ownerId = await getEffectiveOwnerId(supabase, user.id)
  const db      = createServiceClient()

  const { data, error } = await db
    .from(TABLE)
    .select('commentary')
    .eq('owner_user_id', ownerId)
    .order('generated_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ commentary: (data?.commentary as BossViewCommentary | null) ?? null })
}

// ─── POST — generate via AI ─────────────────────────────────────────────────
export async function POST() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const ownerId = await getEffectiveOwnerId(supabase, user.id)
  const db      = createServiceClient()

  // Load the current cached payload + ownership.
  const { data: row, error: loadErr } = await db
    .from(TABLE)
    .select('id, payload')
    .eq('owner_user_id', ownerId)
    .order('generated_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  if (loadErr) return NextResponse.json({ error: loadErr.message }, { status: 500 })
  if (!row)    return NextResponse.json({ error: 'No cached boss-view payload — open the page + Refresh first.' }, { status: 400 })

  const payload = row.payload as BossViewPayload

  // ── Build prompt ────────────────────────────────────────────────────────
  // Pull the most relevant numbers + movers so Haiku has enough context to
  // narrate without hallucinating. Keep token count low (Haiku-friendly).
  const lines: string[] = []
  lines.push(`Week: ${payload.weekLabel}`)
  for (const b of payload.brands) {
    for (const m of ['us', 'id'] as const) {
      const t = b.traffic?.[m]
      const r = b.revenue?.[m]
      if (!t && !r) continue
      lines.push(`${b.siteName}-${m.toUpperCase()}: traffic ${t?.thisWeek?.toLocaleString() ?? 'n/a'} (${t?.pct ?? 'n/a'}%), revenue $${(r?.thisWeek ?? 0).toLocaleString()} (${r?.pct ?? 'n/a'}%)`)
    }
    const focus = (b.focusKeywordsUs ?? []).concat(b.focusKeywordsId ?? []).concat(b.focusKeywords ?? []).slice(0, 5)
    for (const k of focus) {
      const usRank = k.us?.thisWeek != null ? `#${k.us.thisWeek}` : '—'
      const idRank = k.id?.thisWeek != null ? `#${k.id.thisWeek}` : '—'
      lines.push(`  Focus KW: "${k.keyword}" — US ${usRank}, ID ${idRank}, ${k.clicks} clicks, $${k.revenue.toFixed(0)} rev`)
    }
  }
  // AI source — top 1-2 per brand for context
  for (const b of payload.brands) {
    const slice = payload.aiSource?.bySite?.[b.siteSlug]
    if (!slice || slice.skipReason) continue
    const totalDelta = slice.prevTotalUsers > 0 ? Math.round((slice.totalUsers - slice.prevTotalUsers) / slice.prevTotalUsers * 100) : null
    lines.push(`AI Source (${b.siteName}): ${slice.totalUsers.toLocaleString()} users (${totalDelta != null ? totalDelta : 'n/a'}% WoW), $${slice.totalRevenue.toFixed(0)} rev`)
  }

  const userPrompt = `You're writing the weekly SEO commentary for an exec Slack post. Generate TWO sentences total.

This week's data:
${lines.join('\n')}

Output STRICT JSON, no preamble, no markdown:
{
  "whyWorked":   "<1 sentence — the single biggest WIN this week. Cite specific number or brand-country. Max 30 words.>",
  "actionTaken": "<1 sentence — the single biggest CONCERN + what to do about it next week. Cite specific number or brand. Max 30 words.>"
}

Rules:
- Be direct + specific (numbers, brand names, kw names if relevant)
- No marketing fluff ("revolutionize", "synergize", "leverage", "immerse")
- If everything is positive, action_taken should still flag the LEAST-improved metric to watch
- If everything is negative, why_worked should flag the LEAST-bad metric as resilient`

  let commentary: BossViewCommentary
  try {
    const resp = await anthropic.messages.create({
      model:      MODEL,
      max_tokens: 400,
      messages:   [{ role: 'user', content: userPrompt }],
    })
    const raw = resp.content[0].type === 'text' ? resp.content[0].text.trim() : ''
    const jsonMatch = raw.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No JSON in AI response')
    const parsed = JSON.parse(jsonMatch[0]) as { whyWorked?: string; actionTaken?: string }
    if (!parsed.whyWorked || !parsed.actionTaken) throw new Error('Missing whyWorked or actionTaken in AI response')
    commentary = {
      whyWorked:     parsed.whyWorked.trim(),
      actionTaken:   parsed.actionTaken.trim(),
      autoGenerated: true,
      generatedAt:   new Date().toISOString(),
      model:         MODEL,
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'AI generation failed'
    console.error('[boss-view commentary]', msg)
    return NextResponse.json({ error: msg }, { status: 500 })
  }

  // Persist back to the cache row
  const { error: updErr } = await db
    .from(TABLE)
    .update({ commentary })
    .eq('id', row.id)
  if (updErr) {
    console.warn('[boss-view commentary] persist failed (returning text anyway):', updErr.message)
  }

  return NextResponse.json({ commentary })
}

// ─── PATCH — save user edits ────────────────────────────────────────────────
export async function PATCH(req: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const ownerId = await getEffectiveOwnerId(supabase, user.id)
  const db      = createServiceClient()

  const body = await req.clone().json().catch(() => ({})) as { whyWorked?: string; actionTaken?: string }
  if (typeof body.whyWorked !== 'string' && typeof body.actionTaken !== 'string') {
    return NextResponse.json({ error: 'whyWorked and/or actionTaken required' }, { status: 400 })
  }

  // Load current commentary so we can merge per-field updates.
  const { data: row, error: loadErr } = await db
    .from(TABLE)
    .select('id, commentary')
    .eq('owner_user_id', ownerId)
    .order('generated_at', { ascending: false })
    .limit(1)
    .maybeSingle()
  if (loadErr) return NextResponse.json({ error: loadErr.message }, { status: 500 })
  if (!row)    return NextResponse.json({ error: 'No cached payload to attach commentary to' }, { status: 400 })

  const prev = (row.commentary as BossViewCommentary | null) ?? {
    whyWorked: '', actionTaken: '', autoGenerated: false, generatedAt: new Date().toISOString(),
  }
  const next: BossViewCommentary = {
    whyWorked:     typeof body.whyWorked   === 'string' ? body.whyWorked.trim()   : prev.whyWorked,
    actionTaken:   typeof body.actionTaken === 'string' ? body.actionTaken.trim() : prev.actionTaken,
    autoGenerated: false,    // any edit marks as human-edited
    generatedAt:   new Date().toISOString(),
    model:         prev.model,
  }

  const { error: updErr } = await db.from(TABLE).update({ commentary: next }).eq('id', row.id)
  if (updErr) return NextResponse.json({ error: updErr.message }, { status: 500 })

  return NextResponse.json({ commentary: next })
}
