import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'
import { getEffectiveOwnerId } from '@/lib/workspace'
import { resolveSiteSlugFromRequest } from '@/lib/sites'
import { maybeAlertTechItem } from '@/lib/slack/tech-item-alert'

export const maxDuration = 15

/**
 * POST /api/content/broken-urls/create-action
 * Body: {
 *   url: string,
 *   classification: 'high-impact-404' | 'low-impact-404' | '5xx' | 'lost-from-gsc',
 *   evidence: string,                        // human-readable summary
 *   historical_impressions?: number,
 * }
 *
 * Creates an seo_action_items row tagged 'technical' with category-specific
 * priority + description. Returns the created action_item id so the UI can
 * link to it.
 *
 * Used by /content/broken-urls when user clicks "Create Action Item" on a
 * card. Also called by 5.1's auto-action cron for high-traffic 404s with
 * historical_impressions > 1000 (no human click needed).
 */
export async function POST(req: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const ownerId  = await getEffectiveOwnerId(supabase, user.id)
  const body     = await req.json().catch(() => ({}))
  const siteSlug = resolveSiteSlugFromRequest(req, body)
  const db       = createServiceClient()

  const { url, classification, evidence, historical_impressions } = body
  if (!url?.trim() || !classification?.trim()) {
    return NextResponse.json({ error: 'url and classification required' }, { status: 400 })
  }

  // Priority + title vary by classification
  let priority: 'high' | 'medium' | 'low' = 'medium'
  let title = ''
  let actionType: string

  switch (classification) {
    case 'high-impact-404':
      priority   = 'high'
      title      = `High-traffic URL went 404: ${url}`
      actionType = 'fix_broken_url_high_traffic'
      break
    case '5xx':
      priority   = 'high'
      title      = `Server error (5xx) on URL: ${url}`
      actionType = 'fix_server_error'
      break
    case 'lost-from-gsc':
      priority   = (historical_impressions ?? 0) > 5000 ? 'high' : 'medium'
      title      = `Page lost from GSC index: ${url}`
      actionType = 'recover_lost_page'
      break
    case 'low-impact-404':
    default:
      priority   = 'low'
      title      = `Broken URL (low traffic): ${url}`
      actionType = 'fix_broken_url'
      break
  }

  // Resolve site_url for action_items
  let siteUrl = `https://www.${siteSlug === 'g2g' ? 'g2g' : 'offgamers'}.com/`
  try {
    const { data: cfg } = await db
      .from('site_configs')
      .select('gsc_property')
      .eq('slug', siteSlug)
      .maybeSingle()
    if (cfg?.gsc_property) siteUrl = String(cfg.gsc_property)
  } catch { /* keep fallback */ }

  // Check if action item already exists for this URL+type — avoid duplicates
  const { data: existing } = await db
    .from('seo_action_items')
    .select('id')
    .eq('owner_user_id', ownerId)
    .eq('site_url', siteUrl)
    .eq('page', url)
    .eq('action_type', actionType)
    .neq('status', 'done')
    .maybeSingle()

  if (existing) {
    return NextResponse.json({
      ok:    true,
      duplicate: true,
      action_item_id: existing.id,
      message: 'Action item already exists for this URL — skipped duplicate.',
    })
  }

  const description = [
    `Classification: ${classification}`,
    historical_impressions ? `Historical GSC impressions (last 90d): ${historical_impressions.toLocaleString()}` : null,
    evidence ? `\nEvidence:\n${evidence}` : null,
    `\nGenerated by /content/broken-urls auto-classifier.`,
  ].filter(Boolean).join('\n')

  const { data: action, error } = await db
    .from('seo_action_items')
    .insert({
      owner_user_id: ownerId,
      site_url:      siteUrl,
      site_slug:     siteSlug,
      page:          url,
      action_type:   actionType,
      title,
      description,
      priority,
      status:        'pending',
      created_via:   'broken-urls-auto-classify',
    })
    .select('id')
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Sprint TECH.REALTIME — fire immediate Slack if priority is high/critical.
  // Best-effort, non-blocking. Sets last_escalated_at to dedupe with weekly digest.
  await maybeAlertTechItem(db, {
    id:            action.id,
    owner_user_id: ownerId,
    site_slug:     siteSlug,
    page:          url,
    title,
    action_type:   actionType,
    priority,
  })

  return NextResponse.json({
    ok:             true,
    action_item_id: action.id,
    classification,
    priority,
  })
}
