// ── Sprint #380 BOSS.VIEW.PDF — HTML template for the Weekly Snapshot PDF ──
//
// Renders a polished, multi-page A4 PDF that mirrors the visual quality of
// the social team's existing Weekly Social Media Report. Key differences vs
// the screen UI in BossViewContent:
//
//   • Light theme — white bg, dark text (#0F1218), high-contrast bar colors.
//     Print-shop style; dark themes look muddy in PDFs.
//   • Branded chrome on EVERY page via CSS `@page` margin boxes
//     (top-left + top-right strings, bottom-left + bottom-right strings,
//     red 4px stripe under the header). Margin boxes are honored natively
//     by Chromium's `page.pdf({ preferCSSPageSize: true })`.
//   • Bright bar charts with value labels above each bar (every 4th bar
//     to avoid crowding). G2G uses #DC2626 red, OffGamers uses #2563EB
//     blue. Revenue overlay = green #10B981 line.
//   • KPI presented as a flat table (no floating cards) with alternating
//     row shading — easier to skim than 4 small cards.
//   • Commentary as full-bleed callouts: green ✓ Why it worked, amber
//     → Action taken. Optional red ! Watch list when commentary suggests
//     one (currently driven only by negative WoW signals in commentary
//     text; no separate field yet).
//   • Methodology footer + page-break-inside rules so charts don't split
//     awkwardly between A4 pages.
//
// The template is a single big function returning an HTML string. Inline
// CSS + inline Chart.js script + a small data block. Puppeteer:
//   1. setContent(html) → loads the page
//   2. waits for `window.kpiReady === true` (the script sets this after
//      all charts paint a single frame)
//   3. page.pdf({ printBackground: true, displayHeaderFooter: false })
//
// We reuse `window.kpiReady` instead of inventing a new signal so the same
// ready timeout logic in `htmlToPdf` (puppeteer-launcher.ts) works without
// branching.

import type { BossViewPayload } from './boss-view'

export interface BossViewCommentary {
  whyWorked:     string
  actionTaken:   string
  autoGenerated: boolean
  generatedAt:   string
  model?:        string
}

export interface BuildBossViewPdfOptions {
  /** Commentary block to render in the callout cards. Pass `null` (or omit)
   *  to skip the commentary section entirely. */
  commentary?: BossViewCommentary | null
}

// ── Brand palette ─────────────────────────────────────────────────────────
// Kept in sync with the brief: G2G=red, OffGamers=blue, Revenue=green.
const PALETTE = {
  ink:        '#0F1218',
  inkSoft:    '#3F4452',
  inkMuted:   '#6B7280',
  paper:      '#FFFFFF',
  paperSoft:  '#F8F9FB',
  rule:       '#D7DCE3',
  ruleSoft:   '#E5E8EE',
  brandRed:   '#DC2626',  // G2G
  brandBlue:  '#2563EB',  // OffGamers
  revGreen:   '#10B981',
  positive:   '#15803D',
  negative:   '#B91C1C',
  watch:      '#B45309',
  focusBg:    '#FFFBEB',
  focusBorder:'#F59E0B',
  goodBg:     '#ECFDF5',
  goodBorder: '#10B981',
  warnBg:     '#FFFBEB',
  warnBorder: '#F59E0B',
  badBg:      '#FEF2F2',
  badBorder:  '#DC2626',
}

// ── Tiny helpers (no `any`) ───────────────────────────────────────────────

function escapeHtml(raw: string): string {
  return raw
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function fmtNum(n: number): string {
  if (!Number.isFinite(n)) return '—'
  if (Math.abs(n) >= 1_000_000) return `${(n/1_000_000).toFixed(1)}M`
  if (Math.abs(n) >= 1_000)     return `${(n/1_000).toFixed(1)}K`
  return Math.round(n).toLocaleString()
}

function fmtUsd(n: number): string {
  if (!Number.isFinite(n)) return '—'
  if (Math.abs(n) >= 1_000_000) return `$${(n/1_000_000).toFixed(1)}M`
  if (Math.abs(n) >= 1_000)     return `$${(n/1_000).toFixed(0)}K`
  return `$${Math.round(n)}`
}

function fmtPct(v: number | null | undefined): string {
  if (v == null || !Number.isFinite(v)) return '—'
  if (Math.abs(v) < 1) return 'flat'
  return v > 0 ? `+${v.toFixed(0)}%` : `${v.toFixed(0)}%`
}

function pctColor(v: number | null | undefined): string {
  if (v == null || !Number.isFinite(v)) return PALETTE.inkMuted
  if (Math.abs(v) < 1) return PALETTE.inkMuted
  return v > 0 ? PALETTE.positive : PALETTE.negative
}

function shortDate(ymd: string): string {
  if (!ymd) return ''
  const d = new Date(ymd + 'T00:00:00')
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function brandColor(slug: string): string {
  return slug === 'g2g' ? PALETTE.brandRed : PALETTE.brandBlue
}

// ── Section builders ──────────────────────────────────────────────────────

// One row of the KPI table. The "FOCUS" banner sits above; this is the
// flat 4×5 grid (brand-market, traffic, traffic WoW, revenue, revenue WoW).
function kpiTable(payload: BossViewPayload): string {
  const rows: string[] = []
  for (const b of payload.brands) {
    for (const m of ['us', 'id'] as const) {
      const t = b.traffic?.[m] ?? { thisWeek: 0, lastWeek: 0, pct: null }
      const r = b.revenue?.[m] ?? { thisWeek: 0, lastWeek: 0, pct: null }
      const label = `${escapeHtml(b.siteName)} · ${m.toUpperCase()}`
      rows.push(`
        <tr>
          <td class="kpi-brand">${label}</td>
          <td class="kpi-num">${fmtNum(t.thisWeek)}</td>
          <td class="kpi-wow" style="color:${pctColor(t.pct)}">${fmtPct(t.pct)}</td>
          <td class="kpi-num">${fmtUsd(r.thisWeek)}</td>
          <td class="kpi-wow" style="color:${pctColor(r.pct)}">${fmtPct(r.pct)}</td>
        </tr>
      `)
    }
  }
  return `
    <table class="kpi-table">
      <thead>
        <tr>
          <th>Brand · Market</th>
          <th>Traffic</th>
          <th>WoW</th>
          <th>Revenue</th>
          <th>WoW</th>
        </tr>
      </thead>
      <tbody>${rows.join('')}</tbody>
    </table>
  `
}

interface HistChartConfig {
  canvasId: string
  title:    string
  color:    string
  labels:   string[]
  clicks:   number[]
  revenue:  number[]
}

// 2×2 grid of historical timeline charts. Bars = clicks (brand color),
// line overlay = revenue (green). Empty buckets render as empty charts
// (defensive against old cached payloads pre Sprint #363).
function historicalCharts(payload: BossViewPayload): { html: string; configs: HistChartConfig[] } {
  const configs: HistChartConfig[] = []
  const cards: string[] = []
  for (const b of payload.brands) {
    for (const m of ['us', 'id'] as const) {
      const buckets = b.historical?.[m] ?? []
      const id = `chart-hist-${b.siteSlug}-${m}`
      configs.push({
        canvasId: id,
        title:    `${b.siteName} · ${m.toUpperCase()}`,
        color:    brandColor(b.siteSlug),
        labels:   buckets.map(x => shortDate(x.weekEnd)),
        clicks:   buckets.map(x => x.clicks),
        revenue:  buckets.map(x => x.revenue),
      })
      cards.push(`
        <div class="hist-card">
          <p class="hist-title">${escapeHtml(b.siteName)} · ${m.toUpperCase()}</p>
          <div class="hist-canvas-wrap">
            <canvas id="${id}" width="540" height="280"></canvas>
          </div>
        </div>
      `)
    }
  }
  return {
    html: `
      <section class="section section-hist">
        <h2 class="section-title">Historical Trend — Last 13 Weeks</h2>
        <p class="section-sub">
          Weekly organic clicks (bars) with organic revenue overlay (green line).
          Thu-to-Wed windows; value labels printed above each bar.
        </p>
        <div class="hist-grid">${cards.join('')}</div>
      </section>
    `,
    configs,
  }
}

interface FocusKwLike {
  keyword:        string
  scope:          'us' | 'id' | 'all'
  clicks:         number
  revenue:        number
  topLandingPage: string
  us: { lastWeek: number | null; thisWeek: number | null }
  id: { lastWeek: number | null; thisWeek: number | null }
}

function rankCell(prev: number | null, cur: number | null): string {
  if (cur == null && prev == null) return '<span class="rank-na">—</span>'
  const curTxt = cur != null ? `#${cur}` : '—'
  let arrow = ''
  let color = PALETTE.inkMuted
  if (prev != null && cur != null) {
    if (cur < prev) {
      arrow = ` ▲${prev - cur}`
      color = PALETTE.positive
    } else if (cur > prev) {
      arrow = ` ▼${cur - prev}`
      color = PALETTE.negative
    } else {
      arrow = ' —'
    }
  }
  return `<span class="rank-val" style="color:${color}">${escapeHtml(curTxt)}${arrow}</span>`
}

function focusTable(kws: FocusKwLike[], showUs: boolean, showId: boolean): string {
  if (kws.length === 0) {
    return '<p class="empty">No keywords cleared the 10 clicks / week threshold this period.</p>'
  }
  const headers = [
    '<th class="left">Keyword</th>',
    '<th class="right">Clicks</th>',
    '<th class="right">Revenue</th>',
    showUs ? '<th class="right">US Rank</th>' : '',
    showId ? '<th class="right">ID Rank</th>' : '',
  ].filter(Boolean).join('')
  const body = kws.map(k => {
    const cells = [
      `<td class="left">
         <span class="kw-name">${escapeHtml(k.keyword)}</span>
         <span class="kw-lp">${escapeHtml(k.topLandingPage || '—')}</span>
       </td>`,
      `<td class="right num">${fmtNum(k.clicks)}</td>`,
      `<td class="right num">${fmtUsd(k.revenue)}</td>`,
      showUs ? `<td class="right num">${rankCell(k.us.lastWeek, k.us.thisWeek)}</td>` : '',
      showId ? `<td class="right num">${rankCell(k.id.lastWeek, k.id.thisWeek)}</td>` : '',
    ].filter(Boolean).join('')
    return `<tr>${cells}</tr>`
  }).join('')
  return `
    <table class="focus-table">
      <thead><tr>${headers}</tr></thead>
      <tbody>${body}</tbody>
    </table>
  `
}

function focusSections(payload: BossViewPayload): string {
  const g2g = payload.brands.find(b => b.siteSlug === 'g2g')
  const og  = payload.brands.find(b => b.siteSlug === 'offgamers')

  const blocks: string[] = []

  if (g2g) {
    const us = (g2g.focusKeywordsUs ?? []) as FocusKwLike[]
    const id = (g2g.focusKeywordsId ?? []) as FocusKwLike[]
    blocks.push(`
      <section class="section">
        <h2 class="section-title">G2G — Top 5 Focus Keywords (split per market)</h2>
        <p class="section-sub">
          Composite z-score of clicks + winner-take-all landing-page revenue, scoped per market.
          Min 10 clicks/week threshold.
        </p>
        <div class="focus-grid">
          <div class="focus-col">
            <p class="focus-col-title">US Market</p>
            ${focusTable(us, true, false)}
          </div>
          <div class="focus-col">
            <p class="focus-col-title">ID Market</p>
            ${focusTable(id, false, true)}
          </div>
        </div>
      </section>
    `)
  }

  if (og) {
    const all = (og.focusKeywords ?? []) as FocusKwLike[]
    blocks.push(`
      <section class="section">
        <h2 class="section-title">OffGamers — Top 5 Focus Keywords (US + ID combined)</h2>
        <p class="section-sub">
          Unified list (smaller portfolio than G2G). Same composite z-score selection, but
          scope = US+ID combined.
        </p>
        ${focusTable(all, true, true)}
      </section>
    `)
  }

  return blocks.join('')
}

function aiSourceSection(payload: BossViewPayload): string {
  const tables: string[] = []
  for (const b of payload.brands) {
    const slice = payload.aiSource?.bySite?.[b.siteSlug]
    if (!slice) continue
    if (slice.skipReason) {
      tables.push(`
        <div class="ai-col">
          <p class="focus-col-title">${escapeHtml(b.siteName)}</p>
          <p class="empty">Not connected — ${escapeHtml(slice.skipReason)}.</p>
        </div>
      `)
      continue
    }
    const rows = slice.sources.map(s => {
      const userPct = s.prevUsers > 0
        ? Math.round(((s.users - s.prevUsers) / s.prevUsers) * 100)
        : null
      const revPct = s.prevRevenue > 0
        ? Math.round(((s.revenue - s.prevRevenue) / s.prevRevenue) * 100)
        : null
      return `
        <tr>
          <td class="left">${escapeHtml(s.label)}</td>
          <td class="right num">${fmtNum(s.users)}</td>
          <td class="right num" style="color:${pctColor(userPct)}">${fmtPct(userPct)}</td>
          <td class="right num">${fmtUsd(s.revenue)}</td>
          <td class="right num" style="color:${pctColor(revPct)}">${fmtPct(revPct)}</td>
        </tr>
      `
    }).join('')
    const totalsUsers = slice.prevTotalUsers > 0
      ? Math.round(((slice.totalUsers - slice.prevTotalUsers) / slice.prevTotalUsers) * 100)
      : null
    const totalsRev = slice.prevTotalRevenue > 0
      ? Math.round(((slice.totalRevenue - slice.prevTotalRevenue) / slice.prevTotalRevenue) * 100)
      : null
    tables.push(`
      <div class="ai-col">
        <p class="focus-col-title">${escapeHtml(b.siteName)}</p>
        <table class="ai-table">
          <thead>
            <tr>
              <th class="left">Source</th>
              <th class="right">Users</th>
              <th class="right">WoW</th>
              <th class="right">Revenue</th>
              <th class="right">WoW</th>
            </tr>
          </thead>
          <tbody>${rows || '<tr><td colspan="5" class="empty">No AI source traffic this week.</td></tr>'}</tbody>
          <tfoot>
            <tr>
              <td class="left">Total</td>
              <td class="right num">${fmtNum(slice.totalUsers)}</td>
              <td class="right num" style="color:${pctColor(totalsUsers)}">${fmtPct(totalsUsers)}</td>
              <td class="right num">${fmtUsd(slice.totalRevenue)}</td>
              <td class="right num" style="color:${pctColor(totalsRev)}">${fmtPct(totalsRev)}</td>
            </tr>
          </tfoot>
        </table>
      </div>
    `)
  }
  return `
    <section class="section">
      <h2 class="section-title">AI Source — ChatGPT · Perplexity · Gemini · Claude · Copilot</h2>
      <p class="section-sub">
        GA4 sessions whose source domain matches one of the AI assistant whitelisted hosts.
        Filtered server-side; doesn't depend on the GA4 "AI Source" channel group being deployed.
      </p>
      <div class="ai-grid">${tables.join('')}</div>
    </section>
  `
}

function commentarySection(commentary: BossViewCommentary | null | undefined): string {
  if (!commentary) return ''
  const why = commentary.whyWorked?.trim()
  const act = commentary.actionTaken?.trim()
  if (!why && !act) return ''

  // Best-effort "watch list" — if action text mentions negative/decline/drop
  // language we surface a red callout. Cheap heuristic; the data model
  // doesn't have an explicit watchList field yet (could be added in a future
  // sprint).
  const watchSignal = /decline|drop|fell|down\s*\d|negative|risk|concern|watch/i.test(act ?? '')

  const blocks: string[] = []
  if (why) {
    blocks.push(`
      <div class="callout callout-good">
        <p class="callout-label">✓ Why it worked</p>
        <p class="callout-body">${escapeHtml(why)}</p>
      </div>
    `)
  }
  if (act) {
    blocks.push(`
      <div class="callout callout-warn">
        <p class="callout-label">→ Action taken / next</p>
        <p class="callout-body">${escapeHtml(act)}</p>
      </div>
    `)
  }
  if (watchSignal && act) {
    blocks.push(`
      <div class="callout callout-bad">
        <p class="callout-label">! Watch list</p>
        <p class="callout-body">Flagged automatically based on language in the action note above. Verify against the historical trend before sharing externally.</p>
      </div>
    `)
  }

  return `
    <section class="section">
      <h2 class="section-title">Commentary</h2>
      <p class="section-sub">
        ${commentary.autoGenerated ? 'AI-suggested narrative,' : 'Human-edited narrative,'} generated ${escapeHtml(new Date(commentary.generatedAt).toLocaleString())}.
      </p>
      <div class="callouts">${blocks.join('')}</div>
    </section>
  `
}

function methodologyFooter(): string {
  return `
    <section class="section methodology">
      <h3>Methodology</h3>
      <p>
        Traffic = Google Search Console organic clicks, market-classified by GSC's
        country dimension (USA/IDN ISO codes accepted alongside common display variants).
        Revenue = GA4 totalRevenue filtered to the Organic channel group (matches the
        "Total revenue" column shown in the GA4 default dashboard). Focus keywords
        are scored by a composite z-score (clicks + landing-page revenue), with
        winner-take-all attribution per landing page and a 10 clicks/week threshold.
        AI Source traffic is a server-side allowlist of assistant domains so the
        report works whether or not your property has the "AI Source" channel group
        deployed. Weekly windows run Thursday → Wednesday to align with the rest of
        the Friday KPI digest.
      </p>
    </section>
  `
}

// ── Chart.js inline script ────────────────────────────────────────────────
//
// Mirrors the pattern from friday-kpi-html.ts: window.__data assignments
// + a self-invoking function that builds each chart + sets window.kpiReady.
// We disable Chart.js animations + responsive sizing so the canvas paints
// synchronously (PDF rendering doesn't tolerate post-paint resize loops).

function chartScript(configs: HistChartConfig[]): string {
  const dataBlob = JSON.stringify(configs)
  return `
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js"></script>
    <script>
      (function () {
        var CONFIGS = ${dataBlob};
        var COLORS = ${JSON.stringify(PALETTE)};

        function fmtNum(n) {
          if (!isFinite(n)) return '';
          if (Math.abs(n) >= 1000000) return (n/1000000).toFixed(1) + 'M';
          if (Math.abs(n) >= 1000)    return (n/1000).toFixed(1) + 'K';
          return Math.round(n).toLocaleString();
        }
        function fmtUsd(n) {
          if (!isFinite(n)) return '';
          if (Math.abs(n) >= 1000000) return '$' + (n/1000000).toFixed(1) + 'M';
          if (Math.abs(n) >= 1000)    return '$' + (n/1000).toFixed(0) + 'K';
          return '$' + Math.round(n);
        }

        // Datalabel plugin (inline) — paints value above the tallest bars,
        // showing every Nth bar so labels don't overlap.
        var labelPlugin = {
          id: 'pdf-bar-labels',
          afterDatasetsDraw: function (chart) {
            var ctx = chart.ctx;
            var ds  = chart.data.datasets[0];
            if (!ds || ds.type === 'line') return;
            var meta = chart.getDatasetMeta(0);
            if (!meta) return;
            ctx.save();
            ctx.font = '600 9px -apple-system, BlinkMacSystemFont, sans-serif';
            ctx.fillStyle = COLORS.ink;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            var n = meta.data.length;
            // Show every 4th bar's value (4-week granularity matches the
            // brief — "value labels printed above each bar (every 4th week
            // to avoid crowding)") + always show the last bar.
            for (var i = 0; i < n; i++) {
              if (i % 4 !== 0 && i !== n - 1) continue;
              var bar = meta.data[i];
              if (!bar) continue;
              var v = ds.data[i];
              if (v == null || v === 0) continue;
              ctx.fillText(fmtNum(v), bar.x, bar.y - 3);
            }
            ctx.restore();
          },
        };

        if (typeof Chart !== 'undefined' && Chart.register) {
          Chart.register(labelPlugin);
        }

        for (var i = 0; i < CONFIGS.length; i++) {
          var cfg = CONFIGS[i];
          var el  = document.getElementById(cfg.canvasId);
          if (!el || typeof Chart === 'undefined') continue;
          var ctx = el.getContext('2d');

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: cfg.labels,
              datasets: [
                {
                  type: 'bar',
                  label: 'Clicks',
                  data:  cfg.clicks,
                  backgroundColor: cfg.color,
                  borderColor:     cfg.color,
                  borderWidth: 0,
                  yAxisID: 'y',
                  order: 2,
                  categoryPercentage: 0.85,
                  barPercentage:      0.95,
                },
                {
                  type: 'line',
                  label: 'Revenue',
                  data:  cfg.revenue,
                  borderColor:     COLORS.revGreen,
                  backgroundColor: COLORS.revGreen,
                  borderWidth: 2,
                  pointRadius: 2,
                  pointHoverRadius: 0,
                  tension: 0.25,
                  yAxisID: 'y1',
                  order: 1,
                  spanGaps: true,
                },
              ],
            },
            options: {
              responsive: false,
              animation:  false,
              maintainAspectRatio: false,
              layout: { padding: { top: 16, right: 6, left: 0, bottom: 0 } },
              plugins: {
                legend: {
                  display:  true,
                  position: 'top',
                  align:    'end',
                  labels: {
                    color: COLORS.inkSoft,
                    font:  { size: 9 },
                    boxWidth: 10,
                    padding: 6,
                  },
                },
                tooltip: { enabled: false },
              },
              scales: {
                x: {
                  ticks: {
                    color: COLORS.inkMuted,
                    font:  { size: 8 },
                    autoSkip: true,
                    maxRotation: 0,
                    callback: function (_v, idx) {
                      // Show only every 4th label on the x-axis so the
                      // datalabel above + the tick below line up.
                      var labels = this.chart.data.labels;
                      if (idx % 4 !== 0 && idx !== labels.length - 1) return '';
                      return labels[idx];
                    },
                  },
                  grid:   { display: false },
                  border: { color: COLORS.ruleSoft },
                },
                y: {
                  position: 'left',
                  ticks: {
                    color: COLORS.inkMuted,
                    font:  { size: 8 },
                    callback: function (v) { return fmtNum(Number(v)); },
                  },
                  grid:   { color: COLORS.ruleSoft },
                  border: { display: false },
                  beginAtZero: true,
                },
                y1: {
                  position: 'right',
                  ticks: {
                    color: COLORS.inkMuted,
                    font:  { size: 8 },
                    callback: function (v) { return fmtUsd(Number(v)); },
                  },
                  grid:   { display: false },
                  border: { display: false },
                  beginAtZero: true,
                },
              },
            },
          });
        }

        // Give Chart.js two animation frames to paint, then flip the ready
        // flag puppeteer is waiting on (htmlToPdf in puppeteer-launcher.ts).
        requestAnimationFrame(function () {
          requestAnimationFrame(function () {
            window.kpiReady = true;
          });
        });
      })();
    </script>
  `
}

// ── Cover/focus banner ────────────────────────────────────────────────────

function coverBanner(payload: BossViewPayload): string {
  // Pick the largest WoW gain across brand-markets for the one-line focus
  // statement. Falls back to a neutral string if nothing's positive.
  let bestLabel = ''
  let bestPct: number | null = null
  for (const b of payload.brands) {
    for (const m of ['us', 'id'] as const) {
      const p = b.traffic?.[m]?.pct
      if (p == null) continue
      if (bestPct == null || p > bestPct) {
        bestPct = p
        bestLabel = `${b.siteName} · ${m.toUpperCase()}`
      }
    }
  }
  const focusLine = bestPct != null && bestPct > 0
    ? `${escapeHtml(bestLabel)} traffic up ${bestPct.toFixed(0)}% WoW — the largest move this week.`
    : 'Mixed week across brands; see commentary for the single biggest story.'

  return `
    <section class="cover">
      <p class="cover-eyebrow">G2G SEO TOOLS · WEEKLY SNAPSHOT</p>
      <h1 class="cover-title">Weekly Snapshot</h1>
      <p class="cover-sub">${escapeHtml(payload.weekLabel)} · G2G × OffGamers</p>
      <div class="focus-banner">
        <span class="focus-banner-label">FOCUS</span>
        <span class="focus-banner-body">${focusLine}</span>
      </div>
    </section>
  `
}

// ── Main entry point ──────────────────────────────────────────────────────

export function buildBossViewPdfHtml(
  payload: BossViewPayload,
  opts: BuildBossViewPdfOptions = {},
): string {
  const commentary = opts.commentary ?? null
  const hist       = historicalCharts(payload)

  // CSS @page margin boxes pull from `string-set` declarations on the body
  // so the header/footer text can include dynamic week label + a section
  // tag (we don't update the section tag mid-document — left static for
  // now; future enhancement could split sections into @page named regions).
  const headerLeftRaw  = 'G2G SEO TOOLS · Weekly Snapshot'
  const headerRightRaw = escapeHtml(payload.weekLabel)
  const footerLeftRaw  = `${escapeHtml(payload.weekLabel)} · ${shortDate(payload.curStart)}–${shortDate(payload.curEnd)}`

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Weekly Snapshot — ${escapeHtml(payload.weekLabel)}</title>
  <style>
    /* ── Page chrome (Chromium @page support) ────────────────────────── */
    @page {
      size: A4;
      margin: 22mm 14mm 18mm 14mm;

      /* Top-left + top-right: branded header strings. The 4px red stripe
         lives at the bottom of the top margin via border. */
      @top-left {
        content: "${headerLeftRaw}";
        font: 600 8.5pt -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        color: ${PALETTE.ink};
        vertical-align: bottom;
        padding-bottom: 6pt;
        border-bottom: 3px solid ${PALETTE.brandRed};
        width: 100%;
      }
      @top-right {
        content: "${headerRightRaw}";
        font: 500 8.5pt -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        color: ${PALETTE.inkMuted};
        vertical-align: bottom;
        padding-bottom: 6pt;
        border-bottom: 3px solid ${PALETTE.brandRed};
      }
      @bottom-left {
        content: "${footerLeftRaw}";
        font: 400 8pt -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        color: ${PALETTE.inkMuted};
      }
      @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font: 400 8pt -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        color: ${PALETTE.inkMuted};
      }
    }

    /* ── Base typography ─────────────────────────────────────────────── */
    * { box-sizing: border-box; }
    html, body {
      margin: 0; padding: 0;
      background: ${PALETTE.paper};
      color: ${PALETTE.ink};
      font: 10pt/1.45 -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      -webkit-font-smoothing: antialiased;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    /* ── Cover area ──────────────────────────────────────────────────── */
    .cover {
      padding: 4mm 0 6mm 0;
      border-bottom: 1px solid ${PALETTE.ruleSoft};
      margin-bottom: 6mm;
    }
    .cover-eyebrow {
      margin: 0 0 2mm 0;
      font-size: 8pt;
      font-weight: 700;
      letter-spacing: 0.18em;
      color: ${PALETTE.brandRed};
    }
    .cover-title {
      margin: 0 0 1mm 0;
      font-size: 24pt;
      font-weight: 800;
      line-height: 1.1;
      color: ${PALETTE.ink};
    }
    .cover-sub {
      margin: 0 0 4mm 0;
      font-size: 10pt;
      color: ${PALETTE.inkSoft};
    }
    .focus-banner {
      display: flex;
      align-items: stretch;
      background: ${PALETTE.focusBg};
      border-left: 4pt solid ${PALETTE.focusBorder};
      border-radius: 2pt;
      padding: 3mm 3mm;
      gap: 4mm;
    }
    .focus-banner-label {
      font-size: 8pt;
      font-weight: 800;
      letter-spacing: 0.16em;
      color: ${PALETTE.watch};
      align-self: center;
      padding-right: 4mm;
      border-right: 1px solid ${PALETTE.focusBorder};
    }
    .focus-banner-body {
      font-size: 10pt;
      color: ${PALETTE.ink};
      flex: 1;
      align-self: center;
    }

    /* ── Sections ───────────────────────────────────────────────────── */
    .section {
      margin: 0 0 6mm 0;
      page-break-inside: avoid;
    }
    .section-hist { page-break-inside: auto; }   /* chart grid can split if needed */
    .section-title {
      margin: 0 0 1mm 0;
      font-size: 13pt;
      font-weight: 700;
      color: ${PALETTE.ink};
    }
    .section-sub {
      margin: 0 0 3mm 0;
      font-size: 9pt;
      color: ${PALETTE.inkMuted};
      max-width: 170mm;
    }
    .empty {
      font-size: 9pt;
      color: ${PALETTE.inkMuted};
      font-style: italic;
      padding: 2mm 0;
    }

    /* ── KPI table ──────────────────────────────────────────────────── */
    .kpi-table {
      width: 100%;
      border-collapse: collapse;
      border: 1px solid ${PALETTE.rule};
      border-radius: 2pt;
      overflow: hidden;
    }
    .kpi-table thead th {
      background: ${PALETTE.paperSoft};
      border-bottom: 1px solid ${PALETTE.rule};
      padding: 2.5mm 3mm;
      font-size: 8pt;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: ${PALETTE.inkSoft};
      text-align: left;
    }
    .kpi-table thead th + th { text-align: right; }
    .kpi-table tbody tr:nth-child(even) td { background: ${PALETTE.paperSoft}; }
    .kpi-table td {
      padding: 2.5mm 3mm;
      border-top: 1px solid ${PALETTE.ruleSoft};
      font-size: 10pt;
    }
    .kpi-brand { font-weight: 600; color: ${PALETTE.ink}; }
    .kpi-num   { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; }
    .kpi-wow   { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; }

    /* ── Historical charts ─────────────────────────────────────────── */
    .hist-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 4mm;
    }
    .hist-card {
      border: 1px solid ${PALETTE.rule};
      border-radius: 2pt;
      padding: 3mm;
      background: ${PALETTE.paper};
      page-break-inside: avoid;
    }
    .hist-title {
      margin: 0 0 2mm 0;
      font-size: 9pt;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: ${PALETTE.inkSoft};
    }
    .hist-canvas-wrap {
      width: 100%;
      height: 50mm;
      position: relative;
    }
    .hist-canvas-wrap canvas {
      width: 100% !important;
      height: 100% !important;
    }

    /* ── Focus KW + AI source tables ───────────────────────────────── */
    .focus-grid, .ai-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 4mm;
    }
    .focus-col-title {
      margin: 0 0 1.5mm 0;
      font-size: 8pt;
      font-weight: 700;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: ${PALETTE.inkMuted};
    }
    .focus-table, .ai-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 9pt;
    }
    .focus-table thead th, .ai-table thead th {
      background: ${PALETTE.paperSoft};
      padding: 2mm 2mm;
      font-size: 7.5pt;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: ${PALETTE.inkSoft};
      border-bottom: 1px solid ${PALETTE.rule};
    }
    .focus-table tbody tr:nth-child(even) td,
    .ai-table tbody tr:nth-child(even) td { background: ${PALETTE.paperSoft}; }
    .focus-table td, .ai-table td {
      padding: 2mm 2mm;
      border-top: 1px solid ${PALETTE.ruleSoft};
      vertical-align: top;
    }
    .ai-table tfoot td {
      padding: 2mm 2mm;
      border-top: 2px solid ${PALETTE.rule};
      font-weight: 700;
      background: ${PALETTE.paperSoft};
    }
    .focus-table .left, .ai-table .left { text-align: left; }
    .focus-table .right, .ai-table .right { text-align: right; }
    .focus-table .num, .ai-table .num { font-variant-numeric: tabular-nums; }
    .kw-name { display: block; font-weight: 600; color: ${PALETTE.ink}; }
    .kw-lp   { display: block; font-size: 7.5pt; color: ${PALETTE.inkMuted}; word-break: break-all; }
    .rank-val { font-weight: 600; }
    .rank-na  { color: ${PALETTE.inkMuted}; }

    /* ── Commentary callouts ───────────────────────────────────────── */
    .callouts { display: flex; flex-direction: column; gap: 3mm; }
    .callout {
      border-left: 4pt solid;
      padding: 3mm 4mm;
      border-radius: 1pt;
      page-break-inside: avoid;
    }
    .callout-label {
      margin: 0 0 1mm 0;
      font-size: 8.5pt;
      font-weight: 800;
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }
    .callout-body {
      margin: 0;
      font-size: 10.5pt;
      line-height: 1.5;
      color: ${PALETTE.ink};
    }
    .callout-good { background: ${PALETTE.goodBg}; border-color: ${PALETTE.goodBorder}; }
    .callout-good .callout-label { color: ${PALETTE.positive}; }
    .callout-warn { background: ${PALETTE.warnBg}; border-color: ${PALETTE.warnBorder}; }
    .callout-warn .callout-label { color: ${PALETTE.watch}; }
    .callout-bad  { background: ${PALETTE.badBg}; border-color: ${PALETTE.badBorder}; }
    .callout-bad  .callout-label { color: ${PALETTE.negative}; }

    /* ── Methodology footer ────────────────────────────────────────── */
    .methodology {
      margin-top: 8mm;
      padding-top: 4mm;
      border-top: 1px solid ${PALETTE.ruleSoft};
    }
    .methodology h3 {
      margin: 0 0 2mm 0;
      font-size: 9pt;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: ${PALETTE.inkMuted};
    }
    .methodology p {
      margin: 0;
      font-size: 8.5pt;
      line-height: 1.55;
      color: ${PALETTE.inkMuted};
      font-style: italic;
      max-width: 175mm;
    }
  </style>
</head>
<body>
  ${coverBanner(payload)}

  <section class="section">
    <h2 class="section-title">Key Performance Indicators</h2>
    <p class="section-sub">
      Traffic and revenue per brand × market for the current Thu–Wed window with week-over-week deltas.
    </p>
    ${kpiTable(payload)}
  </section>

  ${hist.html}

  ${focusSections(payload)}

  ${aiSourceSection(payload)}

  ${commentarySection(commentary)}

  ${methodologyFooter()}

  ${chartScript(hist.configs)}
</body>
</html>`
}
