-- Sprint #374 BOSS.VIEW.COMMENTARY —
-- Add commentary column to the boss view cache so the "Why it worked" /
-- "Action taken" text persists between page loads + flows into the
-- published-snapshot payload via the publish endpoint.
--
-- Shape stored:
--   {
--     "whyWorked":    "1-2 sentence narrative about biggest win",
--     "actionTaken":  "1-2 sentence narrative about biggest decline + fix",
--     "autoGenerated": true|false,  // false after user edits
--     "generatedAt":  ISO8601,
--     "model":        "claude-haiku-4-5-20251001"
--   }

ALTER TABLE public.friday_kpi_boss_view_cache
  ADD COLUMN IF NOT EXISTS commentary jsonb;

COMMENT ON COLUMN public.friday_kpi_boss_view_cache.commentary IS
  'Editable commentary for boss view Slack post. AI-suggested via Haiku, user-overridable. See Sprint #374.';

NOTIFY pgrst, 'reload schema';
