-- ── Weekly report public access + curatorial flow ───────────────────────
-- Sprint WEEKLY.PUBLIC — adds the columns needed to:
--   (a) Surface the report at a public, login-free URL using a UUID token
--       so CEOs / cross-team viewers can read without an account
--   (b) Distinguish "draft" (generated by Monday-01:00-UTC cron) from
--       "published" (Slack-posted at Monday-08:00-UTC / 15:00 WIB) so the
--       SEO lead has ~7 hours to edit before auto-publish
--   (c) Optionally HOLD a draft (status='held') if the AI output is bad
--       and shouldn't be auto-published

ALTER TABLE public.weekly_reports
  ADD COLUMN IF NOT EXISTS public_token  uuid UNIQUE DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS publish_status text NOT NULL DEFAULT 'published'
    CHECK (publish_status IN ('draft', 'approved', 'published', 'held', 'auto_published')),
  ADD COLUMN IF NOT EXISTS published_at  timestamptz,
  ADD COLUMN IF NOT EXISTS slack_ts      text,    -- Slack message_ts for future chat.update
  /** Edited content overrides — captures Galih's review edits before publish.
      JSONB schema: { narrative?, action_plan?, watch_list?, top_priorities?[] }.
      When non-null, these REPLACE the AI-generated equivalents at publish time. */
  ADD COLUMN IF NOT EXISTS curatorial_edits jsonb;

-- Backfill existing rows so they have valid public_tokens
UPDATE public.weekly_reports
SET public_token = gen_random_uuid()
WHERE public_token IS NULL;

-- Backfill: any existing rows that have already been sent to Slack get 'published'
-- Future rows from cron generate as 'draft' until 08:00 UTC publisher sweeps them.

CREATE INDEX IF NOT EXISTS weekly_reports_public_token_idx
  ON public.weekly_reports (public_token);

CREATE INDEX IF NOT EXISTS weekly_reports_pending_publish_idx
  ON public.weekly_reports (publish_status, week_start)
  WHERE publish_status IN ('draft', 'approved');

COMMENT ON COLUMN public.weekly_reports.public_token IS
  'UUID token for login-free public URL at /public/weekly/[token]. Revocable by setting to NULL.';
COMMENT ON COLUMN public.weekly_reports.publish_status IS
  'Lifecycle: draft (cron-generated) → approved (human approved) → published / auto_published / held';
COMMENT ON COLUMN public.weekly_reports.curatorial_edits IS
  'Human edits applied at publish time. JSONB: { narrative, action_plan, watch_list, top_priorities[] }.';
