-- ── Top Product Tracker seed from SEMrush position tracking CSV ─────────────
-- Run AFTER add_tracked_products.sql migration.
-- Replace the placeholder UUID below with your actual user_id from Supabase Auth > Users.

DO $$
DECLARE v_owner uuid := '00000000-0000-0000-0000-000000000000'; -- ← REPLACE THIS
BEGIN

-- Only insert if table is empty (idempotent)
IF NOT EXISTS (SELECT 1 FROM public.tracked_products WHERE owner_user_id = v_owner LIMIT 1) THEN

INSERT INTO public.tracked_products (id, owner_user_id, name, page_url, keywords, market, active, notes, created_at, updated_at)
VALUES
  (gen_random_uuid(), v_owner, 'Adobe Creative Cloud Gift Cards', 'https://www.g2g.com/categories/adobe-creative-cloud-gift-cards', ARRAY['adobe creative cloud code'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Aeris2 Gift Cards', 'https://www.g2g.com/categories/aeris2-gift-cards', ARRAY['aeris2 vouchers'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Albion Online Global Gold', 'https://www.g2g.com/categories/albion-online-global-gold', ARRAY['albion online silver'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Alipay Gift Cards', 'https://www.g2g.com/categories/alipay-gift-cards', ARRAY['alipay gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Amazon Gift Cards', 'https://www.g2g.com/categories/amazon-gift-cards', ARRAY['buy amazon gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Apex Legends Boosting Service', 'https://www.g2g.com/categories/apex-legends-boosting-service', ARRAY['apex legends boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Apex Legends Game Coaching', 'https://www.g2g.com/categories/apex-legends-game-coaching', ARRAY['apex coach'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Astropay Gift Cards', 'https://www.g2g.com/categories/astropay-gift-cards', ARRAY['astropay voucher'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Bigo Live Top Up', 'https://www.g2g.com/categories/bigo-live-top-up', ARRAY['bigo diamonds'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Bitcash Gift Cards', 'https://www.g2g.com/categories/bitcash-gift-cards', ARRAY['bitcash gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Black Desert Online Boosting Service', 'https://www.g2g.com/categories/black-desert-online-boosting-service', ARRAY['black desert boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Blizzard Gift Cards', 'https://www.g2g.com/categories/blizzard-gift-cards', ARRAY['blizzard gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Bns Neo Divine Gems', 'https://www.g2g.com/categories/bns-neo-divine-gems', ARRAY['bns neo divine gems'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Brawl Stars Top Up', 'https://www.g2g.com/categories/brawl-stars-top-up', ARRAY['brawl stars top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Celcom Gift Cards', 'https://www.g2g.com/categories/celcom-gift-cards', ARRAY['celcom prepaid'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Cgpt Accounts', 'https://www.g2g.com/categories/cgpt-accounts', ARRAY['chatgpt accounts'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Coc1 Account For Sale', 'https://www.g2g.com/categories/coc1-account-for-sale', ARRAY['coc account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Cod Account', 'https://www.g2g.com/categories/cod-account', ARRAY['buy call of duty account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Cod Game Coaching', 'https://www.g2g.com/categories/cod-game-coaching', ARRAY['cod coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Counter Strike Global Offensive Accounts', 'https://www.g2g.com/categories/counter-strike-global-offensive-accounts', ARRAY['cs go accounts','cs2 account','buy counter strike 2 skins'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Cr Coaching', 'https://www.g2g.com/categories/cr-coaching', ARRAY['cr coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Daddyskins Gift Card', 'https://www.g2g.com/categories/daddyskins-gift-card', ARRAY['daddyskins gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dark And Darker Items', 'https://www.g2g.com/categories/dark-and-darker-items', ARRAY['dark and darker item'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dc Gift Cards', 'https://www.g2g.com/categories/dc-gift-cards', ARRAY['cheap discord nitro'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 2 Resurrected Item For Sale', 'https://www.g2g.com/categories/diablo-2-resurrected-item-for-sale', ARRAY['d2r item'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 4 Account', 'https://www.g2g.com/categories/diablo-4-account', ARRAY['diablo 4 account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 4 Boosting Service', 'https://www.g2g.com/categories/diablo-4-boosting-service', ARRAY['diablo 4 boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 4 Game Coaching', 'https://www.g2g.com/categories/diablo-4-game-coaching', ARRAY['diablo 4 coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 4 Gold', 'https://www.g2g.com/categories/diablo-4-gold', ARRAY['diablo 4 gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Diablo 4 Item Buy', 'https://www.g2g.com/categories/diablo-4-item-buy', ARRAY['d4 items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Digimon Master Online Global Item', 'https://www.g2g.com/categories/digimon-master-online-global-item', ARRAY['dmo items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Disney Accounts', 'https://www.g2g.com/categories/disney-accounts', ARRAY['buy disney plus subscription'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dofus Global Kamas', 'https://www.g2g.com/categories/dofus-global-kamas', ARRAY['dofus global kamas'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dota 2 Game Coaching', 'https://www.g2g.com/categories/dota-2-game-coaching', ARRAY['dota 2 coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dota 2 Skins', 'https://www.g2g.com/categories/dota-2-skins', ARRAY['buy dota 2 skins'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dragon Ball Sparking Zero Accounts', 'https://www.g2g.com/categories/dragon-ball-sparking-zero-accounts', ARRAY['dragon ball sparkling zero account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Dungeon Fighter Online Gold', 'https://www.g2g.com/categories/dungeon-fighter-online-gold', ARRAY['dfo gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Ea Play Gift Cards', 'https://www.g2g.com/categories/ea-play-gift-cards', ARRAY['buy ea play pro gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Ebay Gift Cards', 'https://www.g2g.com/categories/ebay-gift-cards', ARRAY['buy ebay gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Escape From Tarkov Accounts', 'https://www.g2g.com/categories/escape-from-tarkov-accounts', ARRAY['escape from tarkov account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Escape From Tarkov Boosting Service', 'https://www.g2g.com/categories/escape-from-tarkov-boosting-service', ARRAY['escape from tarkov top up','eft boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Escape From Tarkov Item', 'https://www.g2g.com/categories/escape-from-tarkov-item', ARRAY['escape from tarkov item'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Eso Boosting Service', 'https://www.g2g.com/categories/eso-boosting-service', ARRAY['eso boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Eso Gold', 'https://www.g2g.com/categories/eso-gold', ARRAY['eso gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Eso Item', 'https://www.g2g.com/categories/eso-item', ARRAY['buy elder scrolls online items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Eve Item', 'https://www.g2g.com/categories/eve-item', ARRAY['eve items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Express Vpn Gift Cards', 'https://www.g2g.com/categories/express-vpn-gift-cards', ARRAY['express vpn 1 month key'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Farmskins Gift Cards', 'https://www.g2g.com/categories/farmskins-gift-cards', ARRAY['farmskins gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Fc 25 Accounts', 'https://www.g2g.com/categories/fc-25-accounts', ARRAY['fc 25 account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Fc 25 Coins', 'https://www.g2g.com/categories/fc-25-coins', ARRAY['fc 25 coins'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Final Fantasy Xiv Arr Boosting Service', 'https://www.g2g.com/categories/final-fantasy-xiv-arr-boosting-service', ARRAY['ffxiv boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Final Fantasy Xiv Arr Gil For Sale', 'https://www.g2g.com/categories/final-fantasy-xiv-arr-gil-for-sale', ARRAY['buy ffxiv gil'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Fn Account', 'https://www.g2g.com/categories/fn-account', ARRAY['fn account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Fn Game Coaching', 'https://www.g2g.com/categories/fn-game-coaching', ARRAY['fn coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Fo76 Items', 'https://www.g2g.com/categories/fo76-items', ARRAY['buy fallout 76 items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Gi Account', 'https://www.g2g.com/categories/gi-account', ARRAY['genshin impact account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Gi Crystals Top Up', 'https://www.g2g.com/categories/gi-crystals-top-up', ARRAY['genshin impact top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Googleplay Gift Cards', 'https://www.g2g.com/categories/googleplay-gift-cards', ARRAY['cheap google play gift cards','google play gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Growtopia Item', 'https://www.g2g.com/categories/growtopia-item', ARRAY['buy growtopia items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Gw2 Boosting Service', 'https://www.g2g.com/categories/gw2-boosting-service', ARRAY['gw2 boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'H Impact 3 Crystals Top Up', 'https://www.g2g.com/categories/h-impact-3-crystals-top-up', ARRAY['honkai impact top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Honor Of Kings Game Coaching', 'https://www.g2g.com/categories/honor-of-kings-game-coaching', ARRAY['honor of kings coach'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Jetoncash Gift Cards', 'https://www.g2g.com/categories/jetoncash-gift-cards', ARRAY['buy jetoncash'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Karma Koin Gift Cards', 'https://www.g2g.com/categories/karma-koin-gift-cards', ARRAY['nexon game card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Killing Floor 2 Skins', 'https://www.g2g.com/categories/killing-floor-2-skins', ARRAY['buy killing floor 2 skins'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Kxz Gift Cards', 'https://www.g2g.com/categories/kxz-gift-cards', ARRAY['kxz gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'League Of Legends Account', 'https://www.g2g.com/categories/league-of-legends-account', ARRAY['buy lol account','lol account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'League Of Legends Boosting Service', 'https://www.g2g.com/categories/league-of-legends-boosting-service', ARRAY['lol boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'League Of Legends Game Coaching', 'https://www.g2g.com/categories/league-of-legends-game-coaching', ARRAY['lol coaching','lol coach'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'League Of Legends Item', 'https://www.g2g.com/categories/league-of-legends-item', ARRAY['buy lol items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'League Of Legends Wild Rift Top Up', 'https://www.g2g.com/categories/league-of-legends-wild-rift-top-up', ARRAY['lol wild rift top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Lineage 2 Adena', 'https://www.g2g.com/categories/lineage-2-adena', ARRAY['l2 adena'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Lost Ark Gold', 'https://www.g2g.com/categories/lost-ark-gold', ARRAY['lost ark gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Lost Ark Item', 'https://www.g2g.com/categories/lost-ark-item', ARRAY['lost ark items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Maple Story Global Boosting Service', 'https://www.g2g.com/categories/maple-story-global-boosting-service', ARRAY['maple story boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Marvel Rivals Game Coaching', 'https://www.g2g.com/categories/marvel-rivals-game-coaching', ARRAY['marvel rivals coach','marvel rivals coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Merlis Gift Cards', 'https://www.g2g.com/categories/merlis-gift-cards', ARRAY['merlis top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Mobile Legends Game Coaching', 'https://www.g2g.com/categories/mobile-legends-game-coaching', ARRAY['mlbb coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Mobile Legends Top Up Diamonds', 'https://www.g2g.com/categories/mobile-legends-top-up-diamonds', ARRAY['mobile legends top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'N Vpn Gift Cards', 'https://www.g2g.com/categories/n-vpn-gift-cards', ARRAY['buy nordvpn cheap'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Ncsoft Ncoin Gift Cards', 'https://www.g2g.com/categories/ncsoft-ncoin-gift-cards', ARRAY['ncoin card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Neosurf Voucher Gift Cards', 'https://www.g2g.com/categories/neosurf-voucher-gift-cards', ARRAY['neosurf voucher'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'New World Coins', 'https://www.g2g.com/categories/new-world-coins', ARRAY['new world coin'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Nutaku Gift Cards', 'https://www.g2g.com/categories/nutaku-gift-cards', ARRAY['nutaku gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Obucks Card Gift Cards', 'https://www.g2g.com/categories/obucks-card-gift-cards', ARRAY['buy obucks card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Odin Valhalla Rising Diamonds', 'https://www.g2g.com/categories/odin-valhalla-rising-diamonds', ARRAY['odin valhalla rising diamonds'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Os Gold', 'https://www.g2g.com/categories/os-gold', ARRAY['os gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Overwatch 2 Game Coaching', 'https://www.g2g.com/categories/overwatch-2-game-coaching', ARRAY['overwatch 2 coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Path Of Exile 2 Account', 'https://www.g2g.com/categories/path-of-exile-2-account', ARRAY['poe 2 accounts'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Path Of Exile 2 Boosting Service', 'https://www.g2g.com/categories/path-of-exile-2-boosting-service', ARRAY['poe 2 boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Path Of Exile 2 Currency', 'https://www.g2g.com/categories/path-of-exile-2-currency', ARRAY['poe 2 currency'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Path Of Exile 2 Game Coaching', 'https://www.g2g.com/categories/path-of-exile-2-game-coaching', ARRAY['poe coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Path Of Exile 2 Item', 'https://www.g2g.com/categories/path-of-exile-2-item', ARRAY['path of exile 2 items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Payeer Rewarble Gift Cards', 'https://www.g2g.com/categories/payeer-rewarble-gift-cards', ARRAY['payeer rewarble'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Playpark Gift Cards', 'https://www.g2g.com/categories/playpark-gift-cards', ARRAY['playpark cash'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Playstation Network Gift Cards', 'https://www.g2g.com/categories/playstation-network-gift-cards', ARRAY['psn gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Poe Boosting', 'https://www.g2g.com/categories/poe-boosting', ARRAY['poe boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Poe Currency', 'https://www.g2g.com/categories/poe-currency', ARRAY['poe currency'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Poe Items', 'https://www.g2g.com/categories/poe-items', ARRAY['poe items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Pokemon Go Boosting Service', 'https://www.g2g.com/categories/pokemon-go-boosting-service', ARRAY['pokemon go boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Pokemon Go Top Up Pokecoins', 'https://www.g2g.com/categories/pokemon-go-top-up-pokecoins', ARRAY['pokemon go top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Ppal Wallet Gift Cards', 'https://www.g2g.com/categories/ppal-wallet-gift-cards', ARRAY['buy paypal wallet gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Pubg Mobile Top Up', 'https://www.g2g.com/categories/pubg-mobile-top-up', ARRAY['pubg mobile top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Razer Gold Gift Cards', 'https://www.g2g.com/categories/razer-gold-gift-cards', ARRAY['buy razer gold gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rbl Item', 'https://www.g2g.com/categories/rbl-item', ARRAY['buy roblox item'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rewarble Gift Cards', 'https://www.g2g.com/categories/rewarble-gift-cards', ARRAY['rewarble gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Riot Points Gift Cards', 'https://www.g2g.com/categories/riot-points-gift-cards', ARRAY['riot points gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rocket League Game Coaching', 'https://www.g2g.com/categories/rocket-league-game-coaching', ARRAY['rocket league coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rs3 Gold', 'https://www.g2g.com/categories/rs3-gold', ARRAY['rs3 gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rubinum Coin Gift Cards', 'https://www.g2g.com/categories/rubinum-coin-gift-cards', ARRAY['rubinum coins'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Rus Accounts Buy', 'https://www.g2g.com/categories/rus-accounts-buy', ARRAY['rust account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Sansat Iptv Gift Cards', 'https://www.g2g.com/categories/sansat-iptv-gift-cards', ARRAY['sansat iptv accounts'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Sea Of Thieves Boosting Service', 'https://www.g2g.com/categories/sea-of-thieves-boosting-service', ARRAY['sea of thieves boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Spotify Gift Cards', 'https://www.g2g.com/categories/spotify-gift-cards', ARRAY['cheap spotify premium'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Steam Wallet Gift Cards', 'https://www.g2g.com/categories/steam-wallet-gift-cards', ARRAY['buy steam gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Summoners War Account', 'https://www.g2g.com/categories/summoners-war-account', ARRAY['summoners war account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tekken 8 Game Coaching', 'https://www.g2g.com/categories/tekken-8-game-coaching', ARRAY['tekken 8 coaching','tekken 8 coach'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Telkomsel Gift Cards', 'https://www.g2g.com/categories/telkomsel-gift-cards', ARRAY['buy telkomsel prepaid'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tf2 Item', 'https://www.g2g.com/categories/tf2-item', ARRAY['tf2 items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tiktok Top Up', 'https://www.g2g.com/categories/tiktok-top-up', ARRAY['tiktok top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tinder Subscription Gift Cards', 'https://www.g2g.com/categories/tinder-subscription-gift-cards', ARRAY['buy tinder subscription'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tnl Items', 'https://www.g2g.com/categories/tnl-items', ARRAY['throne and liberty items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tnl Lucent', 'https://www.g2g.com/categories/tnl-lucent', ARRAY['throne and liberty lucent','tnl lucent'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tom Clancys Rainbow Six Siege Boosting Service', 'https://www.g2g.com/categories/tom-clancys-rainbow-six-siege-boosting-service', ARRAY['r6s boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tom Clancys Rainbow Six Siege Game Coaching', 'https://www.g2g.com/categories/tom-clancys-rainbow-six-siege-game-coaching', ARRAY['r6 coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Tom Clancys Rainbow Six Siege Top Up', 'https://www.g2g.com/categories/tom-clancys-rainbow-six-siege-top-up', ARRAY['rainbow six top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Touch N Go Gift Cards', 'https://www.g2g.com/categories/touch-n-go-gift-cards', ARRAY['touch''n go gift card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Valorant Account For Sale', 'https://www.g2g.com/categories/valorant-account-for-sale', ARRAY['valorant account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Valorant Boosting Service', 'https://www.g2g.com/categories/valorant-boosting-service', ARRAY['valorant boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Valorant Game Coaching', 'https://www.g2g.com/categories/valorant-game-coaching', ARRAY['valorant coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Valorant Top Up', 'https://www.g2g.com/categories/valorant-top-up', ARRAY['valorant top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Visa Rewarble Gift Cards', 'https://www.g2g.com/categories/visa-rewarble-gift-cards', ARRAY['visa rewarble gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Warframe Item', 'https://www.g2g.com/categories/warframe-item', ARRAY['warframe items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Webmoney Rewarble Gift Cards', 'https://www.g2g.com/categories/webmoney-rewarble-gift-cards', ARRAY['webmoney rewarble gift cards'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Where Winds Meet Gamepal', 'https://www.g2g.com/categories/where-winds-meet-gamepal', ARRAY['wwm lfg','where winds meet lfg'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Windows 10 Pro Gift Cards', 'https://www.g2g.com/categories/windows-10-pro-gift-cards', ARRAY['windows 10 pro key'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Windows 11 Pro Gift Cards', 'https://www.g2g.com/categories/windows-11-pro-gift-cards', ARRAY['windows 11 pro key'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'World Of Warcraft Gift Cards', 'https://www.g2g.com/categories/world-of-warcraft-gift-cards', ARRAY['wow game card','wow prepaid time card'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Account', 'https://www.g2g.com/categories/wow-account', ARRAY['buy wow account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Boosting Service', 'https://www.g2g.com/categories/wow-boosting-service', ARRAY['wow boost'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Boosting Service', 'https://www.g2g.com/categories/wow-classic-boosting-service', ARRAY['wow classic boosting'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Era Account', 'https://www.g2g.com/categories/wow-classic-era-account', ARRAY['wow classic account'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Era Coaching', 'https://www.g2g.com/categories/wow-classic-era-coaching', ARRAY['wow classic era coaching'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Era Item', 'https://www.g2g.com/categories/wow-classic-era-item', ARRAY['buy wow classic items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Era Vanilla Gold', 'https://www.g2g.com/categories/wow-classic-era-vanilla-gold', ARRAY['buy wow classic gold','wow classic era gold','wow classic gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Classic Gold', 'https://www.g2g.com/categories/wow-classic-gold', ARRAY['wow cata gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Game Coaching', 'https://www.g2g.com/categories/wow-game-coaching', ARRAY['wow coaching','wow coach'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Gold', 'https://www.g2g.com/categories/wow-gold', ARRAY['g2g wow gold','wow gold'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wow Item', 'https://www.g2g.com/categories/wow-item', ARRAY['buy wow items'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Wuthering Waves Top Up', 'https://www.g2g.com/categories/wuthering-waves-top-up', ARRAY['wuthering waves top up'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Youtube Gift Cards', 'https://www.g2g.com/categories/youtube-gift-cards', ARRAY['buy youtube premium'], 'us', true, null, now(), now()),
  (gen_random_uuid(), v_owner, 'Zenless Zone Zero Top Up', 'https://www.g2g.com/categories/zenless-zone-zero-top-up', ARRAY['zzz top up'], 'us', true, null, now(), now());

END IF;
END $$;

-- Total: 152 products